title: WorkBuddy
url: https://employees.defence.gov.sg
favicon: /images/SDD_logo.png
colors:
  primary-color: "#32402a"
  secondary-color: "#628eaa"
  media-colors:
    - title: media-color-one
      color: "#6e7b38"
    - title: media-color-two
      color: "#9e9984"
    - title: media-color-three
      color: "#cfd8dd"
    - title: media-color-four
      color: "#00838f"
    - title: media-color-five
      color: "#00838f"
description: MINDEF/SAF Employee landing page
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging-lite.d1agw6ct52tvia.amplifyapp.com
prod: https://master.d281b6ti5k76jd.amplifyapp.com
facebook-pixel: ""
shareicon: /images/shareicon.png
is_government: false
google_analytics_ga4: ""
linkedin-insights: ""
resources_name: announcements
